language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - pip freeze
  - coverage run --source=oprex,parsetab,tests tests.py
after_success:
  coveralls


