
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xb4\xe0\xe7X\x9f\x94\xf0Q\xf62\x13l\xf0\r\xc3\x84'
    
_lr_action_items = {'DEDENT':([8,11,17,18,21,23,24,25,28,29,30,33,34,35,],[12,-6,-14,-8,-14,28,-14,-15,-7,34,-16,-17,-9,-18,]),'QUESTMARK':([10,],[15,]),'INDENT':([3,11,18,],[4,17,24,]),'WHITESPACE':([0,],[2,]),'NEWLINE':([0,6,9,13,14,16,19,20,31,32,],[3,11,-12,18,-12,-10,-13,-11,35,11,]),'LITERAL':([26,27,],[31,-19,]),'SLASH':([3,4,10,15,26,27,],[5,5,16,20,5,-19,]),'VARIABLE':([3,4,5,9,11,14,16,17,18,20,21,24,26,27,28,30,33,34,35,],[6,6,10,10,-6,10,-10,22,-8,-11,22,22,32,-19,-7,-16,-17,-9,-18,]),'EQUALSIGN':([22,32,],[27,27,]),'$end':([0,1,2,3,7,11,12,18,28,34,],[-1,0,-2,-3,-4,-6,-5,-8,-7,-9,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'definition':([17,21,24,26,],[21,21,21,30,]),'oprex':([0,],[1,]),'assignment':([22,32,],[26,26,]),'cell':([5,9,14,],[9,14,14,]),'moreCells':([9,14,],[13,19,]),'definitions':([17,21,24,],[23,25,29,]),'expression':([3,4,26,],[7,8,33,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> oprex","S'",1,None,None,None),
  ('oprex -> <empty>','oprex',0,'p_oprex','oprex.py',153),
  ('oprex -> WHITESPACE','oprex',1,'p_oprex','oprex.py',154),
  ('oprex -> NEWLINE','oprex',1,'p_oprex','oprex.py',155),
  ('oprex -> NEWLINE expression','oprex',2,'p_oprex','oprex.py',156),
  ('oprex -> NEWLINE INDENT expression DEDENT','oprex',4,'p_oprex','oprex.py',157),
  ('expression -> VARIABLE NEWLINE','expression',2,'p_expression','oprex.py',167),
  ('expression -> VARIABLE NEWLINE INDENT definitions DEDENT','expression',5,'p_expression','oprex.py',168),
  ('expression -> SLASH cell moreCells NEWLINE','expression',4,'p_expression','oprex.py',169),
  ('expression -> SLASH cell moreCells NEWLINE INDENT definitions DEDENT','expression',7,'p_expression','oprex.py',170),
  ('cell -> VARIABLE SLASH','cell',2,'p_cell','oprex.py',183),
  ('cell -> VARIABLE QUESTMARK SLASH','cell',3,'p_cell','oprex.py',184),
  ('moreCells -> <empty>','moreCells',0,'p_moreCells','oprex.py',192),
  ('moreCells -> cell moreCells','moreCells',2,'p_moreCells','oprex.py',193),
  ('definitions -> <empty>','definitions',0,'p_definitions','oprex.py',201),
  ('definitions -> definition definitions','definitions',2,'p_definitions','oprex.py',202),
  ('definition -> VARIABLE assignment definition','definition',3,'p_definition','oprex.py',206),
  ('definition -> VARIABLE assignment expression','definition',3,'p_definition','oprex.py',207),
  ('definition -> VARIABLE assignment LITERAL NEWLINE','definition',4,'p_definition','oprex.py',208),
  ('assignment -> EQUALSIGN','assignment',1,'p_assignment','oprex.py',220),
]
